name: smart_invoice_app
description: A Smart Invoice Flutter app.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 10.1.9
  flutter_lints: ^3.0.0
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  csv: ^5.0.2
  intl: ^0.19.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
